services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "2025"
      RAM_SIZE: "16G"
      CPU_CORES: "8"
      DISK_SIZE: "128G"
      USERNAME: "xaver"
      PASSWORD: "root"
      HOME: "${HOME}"
      LANGUAGE: "English"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
      - ./wwwroot:/inetpub/wwwroot
    restart: unless-stopped
    stop_grace_period: 2m

